### PR TITLE
Add Issue template for Component Library

### PR DESCRIPTION
**Pull request by jonathanprozzi**
This PR adds an issue template that we can use for Sage Component Library cards

### CODE REVIEW

**Comment by earth2travis** [comment]
We will have to see how the templates display but the Overview h1 is not descriptive of the the contents. Maybe Overview should be the first h2.

Consider "Name: `<ComponentName />` for h1"

Change:

### Spec questions

To:

## Spec Questions (h2 and capital Q)

And move the Spec Questions heading to the bottom

Change:

investgiation

To:

investigation (spelling)

Change States and Props to h3 (sub-headings of Details)

**Comment by jonathanprozzi** [comment]
> We will have to see how the templates display but the Overview h1 is not descriptive of the the contents. Maybe Overview should be the first h2.
> 
> Consider "Name: `<ComponentName />` for h1"
> 
> Change:
> 
> ### Spec questions
> To:
> 
> ## Spec Questions (h2 and capital Q)
> And move the Spec Questions heading to the bottom
> 
> Change:
> 
> investgiation
> 
> To:
> 
> investigation (spelling)
> 
> Change States and Props to h3 (sub-headings of Details)

Good calls! 

I'll have to see how to review this since I did it from the UI instead of CLI!

**Comment by jonathanprozzi** [comment]
References https://github.com/HausDAO/daohaus-monorepo/issues/34 -- will need to refine this and add Checklists that we determine

**Comment by jonathanprozzi** [comment]
Added this in directly with feedback. Going to close this PR as it's not relevant.

**Pull request closed without merging**
