### PR TITLE
Feature/231 modal component

### PR DESCRIPTION
**Pull request by 0xRowdy**
## GitHub Issue

[GitHub issue](https://github.com/HausDAO/daohaus-monorepo/issues/231)

## Changes

Created the Modal component. Have some follow up questions for design about the overlay, button behavior, etc.
Screen Shot 2022-07-30 at 10 58 29 PM

## Packages Added

rerun `yarn install` for radix dialog component

## Checks

Before making your PR, please check the following:

- [x] Critical lint errors are resolved
- [x] App runs locally
- [x] App builds locally (run the build command for *any impacted package* and check for any errors before the PR)

### CODE REVIEW

**Comment by 0xRowdy** [comment]
When I pulled develop into this branch yarn.lock had conflicts. I went ahead and accepted incoming but prolly shouldn't be included as it is a generated file.

**Review by skuhlmann — APPROVED** [review]
https://media.giphy.com/media/xT1XGRNZKFIzKqWnsc/giphy.gif

**Comment by jordanlesich** [comment]
Let's chat when you get back. Was thinking it would be good to store modal state and a single modal component in a highlevel context.

**Comment by 0xRowdy** [comment]
> Let's chat when you get back. Was thinking it would be good to store modal state and a single modal component in a highlevel context.

Absolutly,
I'm free to chat about it this morning.

**Review by jordanlesich — APPROVED** [review]

**Pull request merged**
