### PR TITLE
feature/add-package-readmes

### PR DESCRIPTION
**Pull request by jonathanprozzi**
## GitHub Issue

#276 

- [x] monorepo (top level)
- [x] apps (top level)
- [x] libs (top level)
- [x] subgraphs
- [x] sdk
- [x] commons
- [x] DAOhaus Connect
- [x] TxBuilder
- [x] summon
- [x] hub
- [x] component library
- [x] helm
- [ ] kubernetes
- [ ] ceramic node
- [ ] subgraph node
- [ ] jobs

## Changes

Work in progress, but will add READMEs to each package and at the top level of the monorepo.

## Packages Added

n/a

## Checks

Before making your PR, please check the following:

- [ ] Critical lint errors are resolved
- [ ] App runs locally
- [ ] App builds locally (run the build command for *any impacted package* and check for any errors before the PR)

### CODE REVIEW

**Comment by jonathanprozzi** [comment]
@earth2travis i removed `contracts` from this list based on our earlier conversation -- that can come later but the Mystics repo is really solid on their README

**Comment by jonathanprozzi** [comment]
DAOhaus Connect added -- covered basic use but can add more robust examples highlighting things such as the Ceramic profile functionality

**Comment by jonathanprozzi** [comment]
Hub is pretty solid, but I definitely need to add more to the Summon README

**Comment by jonathanprozzi** [comment]
Added commons README -- we can definitely add more explanations when we create more robust docs

**Review by skuhlmann — APPROVED** [review]
good to go with fixed links.

**Pull request merged**
